export const PREFECTURES = [
  '北海道','青森県','岩手県','宮城県','秋田県','山形県','福島県',
  '茨城県','栃木県','群馬県','埼玉県','千葉県','東京都','神奈川県',
  '新潟県','富山県','石川県','福井県','山梨県','長野県','岐阜県',
  '静岡県','愛知県','三重県','滋賀県','京都府','大阪府','兵庫県',
  '奈良県','和歌山県','鳥取県','島根県','岡山県','広島県','山口県',
  '徳島県','香川県','愛媛県','高知県','福岡県','佐賀県','長崎県',
  '熊本県','大分県','宮崎県','鹿児島県','沖縄県',
];

export const COUNTRIES: { label: string; code: string }[] = [
  // ── アジア ──────────────────────────────
  { label: '中国', code: 'CHN' },
  { label: '韓国', code: 'KOR' },
  { label: '北朝鮮', code: 'PRK' },
  { label: '台湾', code: 'TWN' },
  { label: 'モンゴル', code: 'MNG' },
  { label: 'ベトナム', code: 'VNM' },
  { label: 'タイ', code: 'THA' },
  { label: 'カンボジア', code: 'KHM' },
  { label: 'ラオス', code: 'LAO' },
  { label: 'ミャンマー', code: 'MMR' },
  { label: 'マレーシア', code: 'MYS' },
  { label: 'シンガポール', code: 'SGP' },
  { label: 'インドネシア', code: 'IDN' },
  { label: 'フィリピン', code: 'PHL' },
  { label: 'ブルネイ', code: 'BRN' },
  { label: 'ティモール・レステ', code: 'TLS' },
  { label: 'インド', code: 'IND' },
  { label: 'パキスタン', code: 'PAK' },
  { label: 'バングラデシュ', code: 'BGD' },
  { label: 'スリランカ', code: 'LKA' },
  { label: 'ネパール', code: 'NPL' },
  { label: 'ブータン', code: 'BTN' },
  { label: 'アフガニスタン', code: 'AFG' },

  // ── 中央アジア ───────────────────────────
  { label: 'カザフスタン', code: 'KAZ' },
  { label: 'ウズベキスタン', code: 'UZB' },
  { label: 'トルクメニスタン', code: 'TKM' },
  { label: 'キルギス', code: 'KGZ' },
  { label: 'タジキスタン', code: 'TJK' },

  // ── 中東 ────────────────────────────────
  { label: 'トルコ', code: 'TUR' },
  { label: 'イラン', code: 'IRN' },
  { label: 'イラク', code: 'IRQ' },
  { label: 'シリア', code: 'SYR' },
  { label: 'ヨルダン', code: 'JOR' },
  { label: 'イスラエル', code: 'ISR' },
  { label: 'レバノン', code: 'LBN' },
  { label: 'イエメン', code: 'YEM' },
  { label: 'サウジアラビア', code: 'SAU' },
  { label: 'アラブ首長国連邦', code: 'ARE' },
  { label: 'オマーン', code: 'OMN' },
  { label: 'クウェート', code: 'KWT' },
  { label: 'バーレーン', code: 'BHR' },
  { label: 'カタール', code: 'QAT' },

  // ── ヨーロッパ西部 ───────────────────────
  { label: 'イギリス', code: 'GBR' },
  { label: 'アイルランド', code: 'IRL' },
  { label: 'フランス', code: 'FRA' },
  { label: 'ドイツ', code: 'DEU' },
  { label: 'オランダ', code: 'NLD' },
  { label: 'ベルギー', code: 'BEL' },
  { label: 'ルクセンブルク', code: 'LUX' },
  { label: 'スイス', code: 'CHE' },
  { label: 'オーストリア', code: 'AUT' },
  { label: 'スペイン', code: 'ESP' },
  { label: 'ポルトガル', code: 'PRT' },
  { label: 'イタリア', code: 'ITA' },
  { label: 'ギリシャ', code: 'GRC' },
  { label: 'マルタ', code: 'MLT' },
  { label: 'デンマーク', code: 'DNK' },
  { label: 'スウェーデン', code: 'SWE' },
  { label: 'ノルウェー', code: 'NOR' },
  { label: 'フィンランド', code: 'FIN' },
  { label: 'アイスランド', code: 'ISL' },

  // ── ヨーロッパ東部・中部 ────────────────
  { label: 'ポーランド', code: 'POL' },
  { label: 'チェコ', code: 'CZE' },
  { label: 'スロバキア', code: 'SVK' },
  { label: 'ハンガリー', code: 'HUN' },
  { label: 'ルーマニア', code: 'ROU' },
  { label: 'ブルガリア', code: 'BGR' },
  { label: 'セルビア', code: 'SRB' },
  { label: 'クロアチア', code: 'HRV' },
  { label: 'スロベニア', code: 'SVN' },
  { label: 'ボスニア・ヘルツェゴビナ', code: 'BIH' },
  { label: 'モンテネグロ', code: 'MNE' },
  { label: '北マケドニア', code: 'MKD' },
  { label: 'アルバニア', code: 'ALB' },
  { label: 'コソボ', code: 'XKX' },
  { label: 'ウクライナ', code: 'UKR' },
  { label: 'モルドバ', code: 'MDA' },
  { label: 'ベラルーシ', code: 'BLR' },
  { label: 'リトアニア', code: 'LTU' },
  { label: 'ラトビア', code: 'LVA' },
  { label: 'エストニア', code: 'EST' },
  { label: 'ロシア', code: 'RUS' },
  { label: 'ジョージア', code: 'GEO' },
  { label: 'アルメニア', code: 'ARM' },
  { label: 'アゼルバイジャン', code: 'AZE' },

  // ── アフリカ北部 ────────────────────────
  { label: 'モロッコ', code: 'MAR' },
  { label: 'アルジェリア', code: 'DZA' },
  { label: 'チュニジア', code: 'TUN' },
  { label: 'リビア', code: 'LBY' },
  { label: 'エジプト', code: 'EGY' },
  { label: 'スーダン', code: 'SDN' },

  // ── アフリカ東部・南部 ───────────────────
  { label: 'エチオピア', code: 'ETH' },
  { label: 'ケニア', code: 'KEN' },
  { label: 'タンザニア', code: 'TZA' },
  { label: 'ウガンダ', code: 'UGA' },
  { label: 'ルワンダ', code: 'RWA' },
  { label: 'マダガスカル', code: 'MDG' },
  { label: 'ジンバブエ', code: 'ZWE' },
  { label: 'ザンビア', code: 'ZMB' },
  { label: 'モザンビーク', code: 'MOZ' },
  { label: '南アフリカ', code: 'ZAF' },
  { label: 'ナミビア', code: 'NAM' },
  { label: 'ボツワナ', code: 'BWA' },

  // ── アフリカ西部・中部 ───────────────────
  { label: 'ナイジェリア', code: 'NGA' },
  { label: 'ガーナ', code: 'GHA' },
  { label: 'セネガル', code: 'SEN' },
  { label: 'コートジボワール', code: 'CIV' },
  { label: 'カメルーン', code: 'CMR' },
  { label: 'コンゴ民主共和国', code: 'COD' },
  { label: 'アンゴラ', code: 'AGO' },

  // ── 北米 ────────────────────────────────
  { label: 'アメリカ合衆国', code: 'USA' },
  { label: 'カナダ', code: 'CAN' },
  { label: 'メキシコ', code: 'MEX' },

  // ── 中米・カリブ ────────────────────────
  { label: 'グアテマラ', code: 'GTM' },
  { label: 'ベリーズ', code: 'BLZ' },
  { label: 'ホンジュラス', code: 'HND' },
  { label: 'エルサルバドル', code: 'SLV' },
  { label: 'ニカラグア', code: 'NIC' },
  { label: 'コスタリカ', code: 'CRI' },
  { label: 'パナマ', code: 'PAN' },
  { label: 'キューバ', code: 'CUB' },
  { label: 'ハイチ', code: 'HTI' },
  { label: 'ドミニカ共和国', code: 'DOM' },
  { label: 'ジャマイカ', code: 'JAM' },

  // ── 南米 ────────────────────────────────
  { label: 'コロンビア', code: 'COL' },
  { label: 'ベネズエラ', code: 'VEN' },
  { label: 'エクアドル', code: 'ECU' },
  { label: 'ペルー', code: 'PER' },
  { label: 'ボリビア', code: 'BOL' },
  { label: 'ブラジル', code: 'BRA' },
  { label: 'パラグアイ', code: 'PRY' },
  { label: 'ウルグアイ', code: 'URY' },
  { label: 'アルゼンチン', code: 'ARG' },
  { label: 'チリ', code: 'CHL' },

  // ── オセアニア ───────────────────────────
  { label: 'オーストラリア', code: 'AUS' },
  { label: 'ニュージーランド', code: 'NZL' },
  { label: 'パプアニューギニア', code: 'PNG' },
  { label: 'フィジー', code: 'FJI' },
  { label: 'パラオ', code: 'PLW' },
  { label: 'グアム（米）', code: 'GUM' },
];
