export const PREFECTURES = [
  '北海道','青森県','岩手県','宮城県','秋田県','山形県','福島県',
  '茨城県','栃木県','群馬県','埼玉県','千葉県','東京都','神奈川県',
  '新潟県','富山県','石川県','福井県','山梨県','長野県','岐阜県',
  '静岡県','愛知県','三重県','滋賀県','京都府','大阪府','兵庫県',
  '奈良県','和歌山県','鳥取県','島根県','岡山県','広島県','山口県',
  '徳島県','香川県','愛媛県','高知県','福岡県','佐賀県','長崎県',
  '熊本県','大分県','宮崎県','鹿児島県','沖縄県',
];

export const COUNTRIES: { label: string; code: string }[] = [
  { label: 'アメリカ合衆国', code: 'USA' },
  { label: 'イギリス', code: 'GBR' },
  { label: 'イタリア', code: 'ITA' },
  { label: 'インド', code: 'IND' },
  { label: 'インドネシア', code: 'IDN' },
  { label: 'ウクライナ', code: 'UKR' },
  { label: 'エジプト', code: 'EGY' },
  { label: 'オーストラリア', code: 'AUS' },
  { label: 'カンボジア', code: 'KHM' },
  { label: '韓国', code: 'KOR' },
  { label: 'ギリシャ', code: 'GRC' },
  { label: 'クロアチア', code: 'HRV' },
  { label: 'スペイン', code: 'ESP' },
  { label: 'タイ', code: 'THA' },
  { label: '台湾', code: 'TWN' },
  { label: 'チェコ', code: 'CZE' },
  { label: '中国', code: 'CHN' },
  { label: 'ドイツ', code: 'DEU' },
  { label: 'ナミビア', code: 'NAM' },
  { label: 'ニュージーランド', code: 'NZL' },
  { label: 'フィリピン', code: 'PHL' },
  { label: 'フランス', code: 'FRA' },
  { label: 'ブラジル', code: 'BRA' },
  { label: 'ベトナム', code: 'VNM' },
  { label: 'ペルー', code: 'PER' },
  { label: 'ポーランド', code: 'POL' },
  { label: 'ポルトガル', code: 'PRT' },
  { label: 'マレーシア', code: 'MYS' },
  { label: 'メキシコ', code: 'MEX' },
  { label: 'モロッコ', code: 'MAR' },
  { label: 'モンゴル', code: 'MNG' },
  { label: 'ルーマニア', code: 'ROU' },
  { label: 'ロシア', code: 'RUS' },
  { label: '南アフリカ', code: 'ZAF' },
];
